require("conf.settings")
require("conf.lazy")
require("conf.keymaps")

require("conf.plugins.autosave")
require("conf.plugins.lspconfig")
require("conf.plugins.completion")
require("conf.plugins.nvimtreesitter")
require("conf.plugins.lualine")
require("conf.plugins.telescope")
require("conf.plugins.dap")
require("conf.plugins.true_zen")
require("conf.plugins.comment")
require("conf.plugins.dapui")
require("conf.plugins.etc")
