-- Generated by nwg-displays on 2026-09-20 at 01:16:46. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@165.02",
    position = "0x0",
    scale = 1.25,
    vrr = 0
})
hl.monitor({
    output = "DP-4",
    mode = "1720x1440@59.94",
    position = "2048x0",
    scale = 1.0,
    vrr = 0
})
