-- Generated by nwg-displays on 2026-06-04 at 20:57:38. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-4",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-4"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-4"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-4"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-4"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "7",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "eDP-1"
})
